server:
  port: 8082
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8030
          order: 0
          predicates:
            - Path=/mini-rp/**
          filters:
#            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback

command:
  fallbackcmd:
    execution:
      isolation:
        thread:
          timeoutInMilliseconds: 5000